# Generated by Django 4.2.1 on 2023-10-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistApp', '0005_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingplatform',
            name='image',
            field=models.ImageField(default=None, upload_to='platform_images/'),
            preserve_default=False,
        ),
    ]
