# Generated by Django 4.2.1 on 2023-10-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistApp', '0006_streamingplatform_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(default=None, upload_to='platform_images/'),
            preserve_default=False,
        ),
    ]
